Controllers/PagesController/CategoriaPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Learn.Models.FrontEnd;
using Learn.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Learn.Controllers.PagesController
{
    [Route("categoria")]

    public class CategoriaPageController : Controller
    {
        private readonly CategoriaRepository _categoriaRepository;

        public CategoriaPageController(CategoriaRepository categoriaRepository)
        {
            _categoriaRepository = categoriaRepository;
        }

        public async Task<IActionResult> Index()
        {
            var produtos = await _categoriaRepository.PegaCategoriasAsync();
            return View(produtos);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Modal(int id)
        {
            var model = new FrontModalProdutoCategoria();
            model.Url = "/api/categoria";

            if (id > 0)
            {
                model.Categoria = await _categoriaRepository.PegaCategoriaAsync(id);
                model.Url = model.Url + "/" + model.Produto.ProdutoId;
                model.Method = "PUT";
            }

            return View(model);
        }
    }
}

Controllers/PagesController/ProdutoPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Learn.Models.FrontEnd;
using Learn.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Learn.Controllers.PagesController
{
    [Route("Produto")]
    public class ProdutoPageController : Controller
    {
        private readonly ProdutoRepository _produtoRepository;
        private readonly CategoriaRepository _categoriaRepository;

        public ProdutoPageController(ProdutoRepository produtoRepository, CategoriaRepository categoriaRepository)
        {
            _produtoRepository = produtoRepository;
            _categoriaRepository = categoriaRepository;
        }

        public async Task<IActionResult> Index()
        {
            var produtos = await _produtoRepository.PegaProdutosAsync();
            return View(produtos);
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Modal(int id)
        {
            var model = new FrontModalProdutoCategoria();
            
            model.Url = "/api/produto";

            if (id > 0)
            {
                model.Produto = await _produtoRepository.PegaProdutoAsync(id);
                model.Url = model.Url + "/" + model.Produto.ProdutoId;
                model.Method = "PUT";
            }

            model.Categorias = await  _categoriaRepository.PegaCategoriasAsync();

            return View(model);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/fixedHeader.bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Learn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProdutoPage" asp-action="Index">Produto</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoriaPage" asp-action="Index">Categoria</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Learn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables/js/responsive.bootstrap.min.js"></script>
    <script src="~/lib/mask-money/jquery.maskMoney.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/loadingoverlay/loadingoverlay.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
@RenderBody()
@RenderSection("Scripts", required: false)